### ISSUE TITLE
Support partial data packages

### ISSUE THREAD

**Issue by aamiaa** [aamiaa/Data-Package-Tool#14]
Discord now allows people to choose what data should be included in their package instead of including everything. Currently the tool will die if any of the folders it uses is missing, but ones like `activity`, `account`, and `servers` could very well be optional.

**Comment by Nejkira** [comment]
I have an objection, the data package tool refuses to let me view my data because I didn't include messages option

**Comment by aamiaa** [comment]
That's intended, the tool mainly displays the data from messages. Without them there's nothing to display.
