### ISSUE TITLE
Issues while loading file

### ISSUE THREAD

**Issue by Kf637** [aamiaa/Data-Package-Tool#9]
Only the servers list work, nothing else. I've tried putting my token in the settings but didn't fix it.

![image](https://github.com/aamiaa/Data-Package-Tool/assets/43268197/664a5bdb-7b0e-420c-84b7-10ebda7ea350)

**Comment by aamiaa** [comment]
This was fixed in [1.0.7.1](https://github.com/aamiaa/Data-Package-Tool/releases/tag/1.0.7.1). Download the latest version and it should work.
